spring.application.name=tpo

# URL con el nombre del esquema 'marketplace' y parámetros de compatibilidad
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=user
spring.datasource.password=rootpassword

# Hibernate crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true